DROP SEQUENCE SEQ_BURGER_BRAND;
DROP SEQUENCE SEQ_BURGER_MENU_CODE;
DROP SEQUENCE SEQ_BURGER_NAME;
DROP SEQUENCE SEQ_BURGER_PRICE;
DROP SEQUENCE SEQ_CATEGORY_BRAND;
DROP SEQUENCE SEQ_ENROLL_DATE;
DROP SEQUENCE SEQ_EMAIL;
DROP SEQUENCE SEQ_USER_ID;
DROP SEQUENCE SEQ_USER_NAME;
DROP SEQUENCE SEQ_USER_PWD;

DROP TABLE TBL_BRAND_CATEGORY;
DROP TABLE TBL_BURGER_MENU;
DROP TABLE "USER";
COMMIT;

CREATE SEQUENCE SEQ_BURGER_CODE;
CREATE SEQUENCE SEQ_USER_CODE;

CREATE TABLE "TBL_BRAND_CATEGORY" 
("CATEGORY_CODE"	NUMBER NOT NULL ,
"CATEGORY_BRAND" VARCHAR2(255) NOT NULL,
"REF_CATEGORY_CODE" NUMBER, 

CONSTRAINT "PK_CATEGORY_CODE" PRIMARY KEY ("CATEGORY_CODE")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
 
 CONSTRAINT "FK_REF_CATEGORY_CODE" FOREIGN KEY ("REF_CATEGORY_CODE")
REFERENCES "TBL_BRAND_CATEGORY" ("CATEGORY_CODE") ENABLE
 ) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON COLUMN "TBL_BRAND_CATEGORY"."CATEGORY_CODE" IS '햄버거코드';
COMMENT ON COLUMN "TBL_BRAND_CATEGORY"."CATEGORY_BRAND" IS '햄버거브랜드';
COMMENT ON COLUMN "TBL_BRAND_CATEGORY"."REF_CATEGORY_CODE" IS '상위햄버거코드';
COMMENT ON TABLE "TBL_BRAND_CATEGORY" IS '햄버거 브랜드';

CREATE TABLE "USER" 
(-- COLUMN LEVEL CONSTRAINT 
"USER_NO" VARCHAR2(255),
"USER_NAME" VARCHAR2(255),
"USER_ID" VARCHAR2(255),
"USER_PWD" VARCHAR2(255) NOT NULL ENABLE,
"ENROLL_DATE" DATE,
"EMAIL"	VARCHAR2(255),
 -- TABLE LEVEL CONSTRAINT
CONSTRAINT "PK_USER_NO" PRIMARY KEY ("USER_NO")
--여기부터
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
--여기까지 무시 
	 UNIQUE ("USER_ID")
--여기부터
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--여기까지 싹 다 무시

COMMENT ON COLUMN "USER"."USER_NO" IS '사용자코드';
COMMENT ON COLUMN "USER"."USER_NAME" IS '이름';
COMMENT ON COLUMN "USER"."USER_ID" IS '아이디';
COMMENT ON COLUMN "USER"."USER_PWD" IS '비밀번호';
COMMENT ON COLUMN "USER"."ENROLL_DATE" IS '가입일';
COMMENT ON COLUMN "USER"."EMAIL" IS '이메일';
COMMENT ON TABLE "USER" IS '사용자';

--버거메뉴 TABLE 만들기
CREATE TABLE "TBL_BURGER_MENU" 
( "MENU_CODE" NUMBER NOT NULL ENABLE,
"MENU_NAME"	VARCHAR2(255)	NOT NULL ENABLE,
"MENU_BRAND"	VARCHAR2(255)	NOT NULL ENABLE,
"MENU_PRICE"	NUMBER	NOT NULL ENABLE,
"MENU_RANK"	NUMBER		NOT NULL ENABLE,
"CATEGORY_CODE" NUMBER NOT NULL ENABLE, 

CONSTRAINT "PK_MENU_CODE" PRIMARY KEY ("MENU_CODE")
--여기부터 무시
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
--여기까지 무시
CONSTRAINT "FK_CATEGORY_CODE" FOREIGN KEY ("CATEGORY_CODE")
REFERENCES "TBL_BRAND_CATEGORY" ("CATEGORY_CODE") ENABLE
--여기부터
   ) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;
--여기까지 싹 다 무시
COMMENT ON COLUMN "TBL_BURGER_MENU"."MENU_CODE" IS '햄버거코드';
COMMENT ON COLUMN "TBL_BURGER_MENU"."MENU_NAME" IS '햄버거이름';
COMMENT ON COLUMN "TBL_BURGER_MENU"."MENU_BRAND" IS '햄버거브랜드';
COMMENT ON COLUMN "TBL_BURGER_MENU"."MENU_PRICE" IS '햄버거가격';
COMMENT ON COLUMN "TBL_BURGER_MENU"."MENU_RANK" IS '버거별점';
COMMENT ON COLUMN "TBL_BURGER_MENU"."CATEGORY_CODE" IS '햄버거코드';
COMMENT ON TABLE "TBL_BURGER_MENU" IS '버거 게시물';

COMMIT;